app:
  name: 'Planning Helper'
  description: Planning api for Konrad Jezierski's bachelors project
server:
  port: 0
http:
  port: 8080
springdoc:
  api-docs:
    path: /swagger-json
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization-inclusion: non_null
    default-property-inclusion: non_null
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  cache:
    cache-names: ''
    redis:
      time-to-live: 1h

  mail:
    from: testmail@test.pl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
in-app-cache:
  valid-time-in-hours: 3
api:
  host: ''
  errors:
    PL.001: The value should be a positive number
    PL.002: This value shound not be empty
    PL.003: This value should be a future date time
    PL.004: Could not process the file
    PL.005: You can only start Planning with SCHEDULED status
    PL.006: You can only close Planning with PROGRESSING or VOTING status
    PL.007: You can only change focus of Planning with PROGRESSING or VOTING status
    PL.008: This value is not valid
    PL.009: You cannot set estimation for not focused item
    PL.010: You can only enable voting of Planning with PROGRESSING status
    PL.011: You can only disable voting of Planning with VOTING status
    PL.012: You can only vote when status of the Planning is VOTING
    PL.013: You can only vote on focused item
    PL.014: You have already voted on this item
    PL.015: You can only clear votes when Planning has PROGRESSING or VOTING status
    PL.016: You can only clear votes from focused item